[tool.poetry]
name = "teste-carga"
version = "0.1.0"
description = ""
authors = ["Camila <bbatistacamila@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
locust = "^2.29.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
